name: Keep HuggingFace Space Alive

on:
  schedule:
    # Every day at 12 PM UTC
    - cron: "0 12 * * *"

  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Wake HuggingFace Space
        run: |
          curl -L "https://anjolaakins-shop-conv.hf.space"
