name: Keep Render Awake

on:
  schedule:
    - cron: "*/10 * * * *"

  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Ping Render App
        run: |
          curl -L "https://shop-conv.onrender.com"
